#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=vllm-small
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=04:00:00
#SBATCH --output=vllm/logs/serve_small_%j.out

set -e

mkdir -p vllm/logs

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1

source $(conda info --base)/etc/profile.d/conda.sh

conda activate vllm-env

python -m vllm.entrypoints.openai.api_server \
    --model Qwen/Qwen2.5-7B-Instruct \
    --port 8267 \
    --max-model-len 8192
