#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=vllm-big
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --time=04:00:00
#SBATCH --output=vllm/logs/serve_big_%j.out

set -e

mkdir -p vllm/logs

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1

source $(conda info --base)/etc/profile.d/conda.sh

conda activate vllm-env

python -m vllm.entrypoints.openai.api_server \
    --model Qwen/Qwen2.5-72B-Instruct \
    --port 8268 \
    --max-model-len 8192 \
    --tensor-parallel-size 2
