#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=4
#SBATCH --job-name=vllm-235b
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=320G
#SBATCH --time=04:00:00
#SBATCH --output=vllm/logs/serve_235b_%j.out

set -e

mkdir -p vllm/logs

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1

source $(conda info --base)/etc/profile.d/conda.sh

conda activate vllm-env

export HF_HOME=/scratch-shared/$USER/.cache/huggingface

python -m vllm.entrypoints.openai.api_server \
    --model Qwen/Qwen3-VL-235B-A22B-Instruct \
    --port 8271 \
    --max-model-len 8192 \
    --tensor-parallel-size 4 \
    --quantization fp8 # due to large size
