#!/bin/bash
#SBATCH --partition=rome
#SBATCH --job-name=spotlight-serve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=28G
#SBATCH --time=24:00:00
#SBATCH --output=spotlight/logs/serve_%j.out

set -e

mkdir -p spotlight/logs

module purge
module load 2023
module load Java/11.0.20

java -Dfile.encoding=UTF-8 -Xmx20G \
    -jar spotlight/dbpedia-spotlight.jar \
    spotlight/models/en \
    http://0.0.0.0:2223/rest
